media:
  input: 'media'               # The folder where uploaded media files are stored
  output: 'media'              # The folder from which media files are served
  path: 'media'                # Default path for the media browser
  extensions:                  # Allowed file extensions
    - jpg
    - jpeg
    - png
    - gif

collections:
  - name: 'pages'              # Unique name for the collection
    label: 'Pages'              # Display name in the CMS
    type: 'collection'          # Type of collection (can be 'collection' or 'file')
    path: 'content/pages'       # Path where page files are stored (you may need to create this folder)
    fields:                     # Define fields for each page entry
      - name: 'title'
        label: 'Title'
        type: 'string'
      - name: 'body'
        label: 'Body'
        type: 'rich-text'
