backend:
  name: github
  repo: yourusername/yourrepository # Replace with your GitHub username and repo name
  branch: main # Replace with your production branch, usually 'main' or 'master'

media_folder: "assets/uploads" # Where images/files will be stored
public_folder: "/assets/uploads" # Public path to the media folder

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
