backend:
  name: git-gateway
  repo: Babasato/familytraveldeals # Replace with your GitHub username and repo name
  branch: main # Replace with your production branch, usually 'main' or 'master'

media_folder: "assets/uploads" # Physical storage path
public_folder: "/assets/uploads" # Public URL path

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts" # Ensure this folder exists in your project
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
